- name: Configure Raspberry Pi for SafeTV project
  hosts: local
  become: yes
  vars:
    app_user: pi
    app_dir: /home/pi/safedo
    venv_path: /home/pi/safedo/venv
    app_file: /home/pi/safedo/app.py
    ssid_name: safetv
    ssid_pass: safetv123

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-venv
          - python3-pip
          - dnsmasq
          - adb
          - nmap
          - iptables-persistent
          - network-manager
          - tailscale
        state: present
        update_cache: yes

    - name: Create virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"

    - name: Copy Flask app (placeholder)
      copy:
        src: ./app.py
        dest: "{{ app_file }}"
        owner: pi
        group: pi
        mode: '0755'

    - name: Install Python requirements in venv
      pip:
        virtualenv: "{{ venv_path }}"
        requirements: ./requirements.txt

    - name: Create systemd service
      template:
        src: templates/safetv.service.j2
        dest: /etc/systemd/system/safetv.service

    - name: Enable and start service
      systemd:
        name: safetv.service
        daemon_reload: yes
        enabled: yes
        state: started

    - name: Configure Wi-Fi Access Point
      shell: |
        nmcli connection add type wifi ifname wlan0 con-name MyAP autoconnect yes ssid "{{ ssid_name }}" \
            wifi.mode ap wifi.band bg wifi.channel 1 \
            802-11-wireless-security.key-mgmt wpa-psk \
            802-11-wireless-security.psk "{{ ssid_pass }}" \
            ipv4.method shared ipv6.method ignore
        nmcli con modify MyAP ipv4.method manual ipv4.addresses 10.1.1.1/24
        nmcli con modify MyAP ipv4.gateway 10.1.1.1
        nmcli con modify MyAP ipv4.dns 8.8.8.8
        nmcli con modify MyAP ipv6.method ignore
      args:
        creates: /etc/NetworkManager/system-connections/MyAP.nmconnection

    - name: Configure dnsmasq
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan0
          dhcp-range=10.1.1.10,10.1.1.50,12h
          dhcp-option=3,10.1.1.1
          dhcp-option=6,8.8.8.8

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure NAT
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: eth0
        jump: MASQUERADE

    - name: Save iptables
      command: netfilter-persistent save

    - name: Restart services
      systemd:
        name: dnsmasq
        state: restarted

    - name: Bring AP up
      shell: |
        nmcli con down MyAP || true
        nmcli con up MyAP

    - name: Install Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      args:
        creates: /usr/sbin/tailscaled

    - name: Enable and start tailscaled
      systemd:
        name: tailscaled
        enabled: yes
        state: started

    - name: Bring Tailscale up with SSH enabled (interactive login)
      shell: tailscale up --ssh
      args:
        creates: /var/lib/tailscale/tailscaled.state

